### ISSUE TITLE
So is DC-Detector effective?

### ISSUE THREAD

**Issue by Leopold2333** [ForestsKing/DCdetector#1]
I note that the **Readme** file lists the result on _SMD_ dataset, that seems not a good result compared with what is mentioned in the paper? Did you get any more experiment results with this version of Code? I'm really interested about it. By the way, just out of curiosity, I want to know about the real ability of DC-Detector.

**Comment by ForestsKing** [comment]
I found that there were many differences between the code of the DCdetector and the paper, so I didn't do any more experiments. If you are interested, you can verify it yourself. Further exchanges are welcome.
